### ISSUE TITLE
Thoughts for extending BreakerState

### ISSUE THREAD

**Issue by tfoote** [fetchrobotics/power_msgs#1]
I saw this come in and had a few thoughts. It would be grea to: 

 * Add a way to indicate no-measurement for temperature and current.  Possibly reuse REP 117 standards? http://www.ros.org/reps/rep-0117.html  (Just a documentation update. )
 * Add a max_current field. That way you know what fraction of the breaker you're using. 
 * Add a max_temperature field. That way you know if you're close to thermal shutdown.

They could also possibly be "rated_current" or "rated_temperater" it's a little bit more application specific, but less intuitive to be read quickly. 

Thoughts?

**Comment by mikeferguson** [comment]
Good ideas, this is definitely still a work in progress, so we can certainly incorporate these. I suppose rep-0117 would work well (we would probably use only nan, I think). I actually think "rated_" is the preferred terminology for the breakers.

My goal is to have generic messages/services so that people stop creating new ones for each robot (pr2, turtlebot, ubr-1 all had their own message, this especially affects re-usability of graphical tools).

**Comment by tfoote** [comment]
Yeah, the power distribution was not something we ironed out generically on the pr2 and no one has put the effort in. I definitely see this as a future component of common_msgs. 

I think I'd still lean toward the max_* since we are specifically stating an uppper bound. The breakers are "rated" down to a certain temperature as well. It could be max_rated_*. 

The benefit of using "rated" is that you understand that this is the specification, not something adjustable by the user.

**Comment by mikeferguson** [comment]
Closed by #2
